//Leilani Horlander-Cruz
//CSCE 121-505
//Due: September 8, 2016
//hw1pr1.cpp

#include "std_lib_facilities_4.h"

int main()
{
	cout << "ACROSS\n"
	     << "1. a procedure or formula for solving a problem;"
	     << " a finite series of computational steps to produce a result.\n"
	     << "2. a program ready to be run (executed) on a computer.\n"
	     << "3. a user-defined type that may contain data members, function members, and member"
	     << " types.\n"
	     << "4. code (possibly with associated data) that is sufficiently complete to be"	
	     << " executed by a computer.\n"
	     << "5. a value used to identify a typed object in memory.\n"
	     << "6. an initialized region of memory of a known type which holds a value of that"
	     << " type.\n"	
	     << "7. a named unit of code that can be invoked (called) from different parts of a"
	     << " program; a logical unit of computation.\n"
	     << "8. something that defines a set of possible values and a set of operations for an"
 	     <<	"  object.\n\n"	
	     << "DOWN\n"
	     << "2. a mismatch between reasonable expectations of program behavior (often expressed"
	     << " as a requirement or a users' guide) and what a program actually does.\n"			 << "9. an operation that initializes an object. Typically establishes an invariant and"
	     << " often acquires resources needed for an object to be used (which are then"
	     << " typically released by a destructor).\n"
	     << "10. giving an object its first value.\n"
	     << "11. the specification of a name with its type in a program.\n"
	     << "12. a standard measure that gives meaning to a value (e.g., km for a distance).\n"
	     << "13. a set of techniques for programming leading to a consistent use of language"
	     << " features; sometimes used in a very restricted sense to refer just to low-level"
	     << " rules for naming and appearance of code.\n"
	     << "14. a sequence of characters.\n\n"

	     << "            9\n"
	     << "             C\n"
	     << "   1             10\n"
	     << "    A  L  G  O  R  I  T  H  M\n\n"
	     << "             N     N\n\n"
	     << "             S     I\n\n"
	     << "             T     T\n"
	     << "                          11\n"
	     << "             R     I        D\n"
	     << "2\n"
	     << " E  X  E  C  U  T  A  B  L  E\n"
	     << "                           3\n"
	     << " R           C     L        C  L  A  S  S\n\n"
	     << " R           T     I        L\n\n"
	     << " O           O     Z        A\n"
	     << "                        4\n"
	     << " R           R     E     P  R  O  G  R  A  M\n\n"
	     << "                            A\n"
	     << "               5\n"
	     << "                P  O  I  N  T  E  R\n"
	     << "                                         14\n"	
	     << "                            I              S\n"
	     << "                 13        6\n"
	     << "                   S        O  B  J  E  C  T\n"
	     << "      7 12\n"
	     << "       F  U  N  C  T  I  O  N              R\n\n"
	     << "          N        Y                       I\n\n"
	     << "          I        L                       N\n"
	     << "         8\n"
	     << "          T  Y  P  E                       G\n";
	return 0;
}
